config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "recipes#index"

  resources :recipes
  get '/rack-headers' => 'rack_headers#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    ip = $geoip.city(request.headers['Fly-Client-Ip']) rescue nil
    @key = nil

    @recipes = if params[:q]
      @key = params[:q]
      Recipe.where("lower(data->>'title') LIKE '%#{params[:q].downcase}%'")
    elsif ip
      @appear = ip.city.name || ip.country.name
      @key = ip
      Recipe.where("lower(data->>'title') LIKE '%#{ip.city.name.downcase}%' OR lower(data->>'title') LIKE '%#{ip.country.name.downcase}%'")
    else
      Recipe.none
    end
  end
end

app/controllers/rack_headers_controller.rb
# frozen_string_literal: true

class RackHeadersController < ApplicationController
  layout false
  def show; end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    ip = $geoip.city(request.headers['Fly-Client-Ip']) rescue nil

    @recipes = if params[:q]
      Recipe.where("lower(data->>'title') LIKE '%#{params[:q].downcase}%'")
    elsif ip
      @appear = ip&.city&.name || ip&.country&.name
      Recipe.where("lower(data->>'title') LIKE '%#{@appear.downcase}%' OR lower(data->>'title') LIKE '%#{ip.country.name.downcase}%'")
    else
      Recipe.none
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/home.html.erb
<div class="flex flex-col min-h-screen items-center pt-20 pb-20 bg-gray-100">
<% if @appear %>
  <p>You appear to be visiting from <%= @appear %>.</p>
<% end %>

<%=form_tag request.path, method: :get, class: "mt-5 sm:flex sm:items-center" do %>
  <div class="w-full sm:max-w-xs">
    <%= text_field_tag :q, params[:q] || @appear, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
  </div>


<%= submit_tag "Go", class: "mt-3 w-full inline-flex items-center justify-center px-4 py-2 border border-transparent shadow-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm" %>
<% end %>
<ul class="divide-y divide-y-gray-200">
<% if @key.present? %>
  <% cache(@key, expires_in: 10.seconds) do %>
    <% @recipes.each do |recipe| %>
    <li class="p-4"><%= recipe.data["title"] %></li>
    <% end %>
  <% end %>
<% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookherenow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", data: { turbo_track: "reload" } %>
    <%= javascript_importmap_tags %>

  </head>

  <body class="h-full">
    <div class="flex flex-col min-h-screen items-center pt-20 pb-20 bg-gray-100">
    <div class="max-w-xl p-4">
      <%= yield %>
    </div>
    </div>
  </body>
</html>

app/views/rack_headers/show.html.erb
<pre>
<% request.headers.each do |k, v| %>
<b><%= k %>: </b> <%= v %>
<% end %>
</pre>

app/views/recipes/_edamam.html.erb
<a href="https://edamam.com">
<svg class="ml-4" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 400 80" style="enable-background:new 0 0 400 80;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#77CC00;}
	.st1{fill:#F4F7FA;}
	.st2{opacity:0.7;fill:#F4F7FA;enable-background:new    ;}
	.st3{fill:#929497;}
</style>
<g id="Layer_1_1_">
</g>
<g id="Layer_2_1_">
	<ellipse class="st0" cx="254.5" cy="40.9" rx="28.6" ry="28.6"/>
	<g>
		<path class="st1" d="M265.7,29.5h-22.3c-0.7,0-1.3-0.6-1.3-1.3v-0.6c0-0.7,0.6-1.3,1.3-1.3h22.3c0.7,0,1.3,0.6,1.3,1.3v0.6
			C267,29,266.4,29.5,265.7,29.5z"/>
		<path class="st1" d="M265.7,42.5h-22.3c-0.7,0-1.3-0.6-1.3-1.3v-0.5c0-0.7,0.6-1.3,1.3-1.3h22.3c0.7,0,1.3,0.6,1.3,1.3v0.5
			C267,41.9,266.4,42.5,265.7,42.5z"/>
		<path class="st1" d="M265.7,55.4h-22.3c-0.7,0-1.3-0.6-1.3-1.3v-0.6c0-0.7,0.6-1.3,1.3-1.3h22.3c0.7,0,1.3,0.6,1.3,1.3v0.6
			C267,54.9,266.4,55.4,265.7,55.4z"/>
		<path class="st2" d="M249.9,36h-6.4c-0.7,0-1.3-0.6-1.3-1.3v-0.5c0-0.7,0.6-1.3,1.3-1.3h6.4c0.7,0,1.3,0.6,1.3,1.3v0.5
			C251.2,35.4,250.6,36,249.9,36z"/>
		<path class="st2" d="M250.1,49h-6.5c-0.7,0-1.3-0.6-1.3-1.3v-0.6c0-0.7,0.6-1.3,1.3-1.3h6.5c0.7,0,1.3,0.6,1.3,1.3v0.6
			C251.3,48.4,250.8,49,250.1,49z"/>
	</g>
</g>
<g id="Layer_3">
	<g>
		<path class="st3" d="M110.5,42.4v4.2h-2V35.2h4.4c1.3,0,2.3,0.3,3,1s1.1,1.5,1.1,2.6s-0.4,2-1.1,2.6s-1.8,0.9-3.1,0.9h-2.3V42.4z
			 M110.5,40.8h2.4c0.7,0,1.2-0.2,1.6-0.5s0.6-0.8,0.6-1.4c0-0.6-0.2-1.1-0.6-1.5s-0.9-0.6-1.5-0.6h-2.4L110.5,40.8L110.5,40.8z"/>
		<path class="st3" d="M129,41.2c0,1.1-0.2,2.1-0.6,2.9c-0.4,0.8-0.9,1.5-1.7,1.9c-0.7,0.5-1.5,0.7-2.5,0.7c-0.9,0-1.7-0.2-2.5-0.7
			c-0.7-0.5-1.3-1.1-1.7-1.9c-0.4-0.8-0.6-1.8-0.6-2.9v-0.6c0-1.1,0.2-2.1,0.6-2.9c0.4-0.8,0.9-1.5,1.7-1.9c0.7-0.5,1.5-0.7,2.5-0.7
			c0.9,0,1.7,0.2,2.5,0.7c0.7,0.4,1.3,1.1,1.7,1.9s0.6,1.8,0.6,2.9V41.2z M127,40.6c0-1.3-0.2-2.2-0.7-2.9s-1.2-1-2-1
			c-0.9,0-1.5,0.3-2,1s-0.7,1.6-0.7,2.8v0.7c0,1.2,0.2,2.2,0.7,2.9s1.2,1,2,1c0.9,0,1.5-0.3,2-1s0.7-1.6,0.7-2.9V40.6z"/>
		<path class="st3" d="M141.1,43.8l1.8-8.6h2l-2.6,11.4h-1.9l-2.2-8.3l-2.2,8.3h-2l-2.6-11.4h2l1.8,8.5l2.2-8.5h1.7L141.1,43.8z"/>
		<path class="st3" d="M154.1,41.5h-4.7V45h5.5v1.6h-7.4V35.2h7.4v1.6h-5.4V40h4.7v1.5H154.1z"/>
		<path class="st3" d="M161.9,42.2h-2.2v4.4h-2V35.2h4c1.3,0,2.3,0.3,3,0.9c0.7,0.6,1.1,1.4,1.1,2.6c0,0.8-0.2,1.4-0.6,1.9
			c-0.4,0.5-0.9,0.9-1.5,1.2l2.6,4.7v0.1h-2.1L161.9,42.2z M159.7,40.6h2c0.7,0,1.2-0.2,1.6-0.5s0.6-0.8,0.6-1.4
			c0-0.6-0.2-1.1-0.5-1.4c-0.3-0.3-0.9-0.5-1.6-0.5h-2.1V40.6z"/>
		<path class="st3" d="M175.5,41.5h-4.7V45h5.5v1.6h-7.4V35.2h7.4v1.6h-5.4V40h4.7v1.5H175.5z"/>
		<path class="st3" d="M179.1,46.6V35.2h3.4c1,0,1.9,0.2,2.7,0.7c0.8,0.4,1.4,1.1,1.8,1.9c0.4,0.8,0.6,1.8,0.6,2.8v0.6
			c0,1.1-0.2,2-0.6,2.8s-1,1.4-1.8,1.9c-0.8,0.4-1.7,0.7-2.7,0.7C182.5,46.6,179.1,46.6,179.1,46.6z M181.1,36.8V45h1.3
			c1,0,1.8-0.3,2.4-1s0.8-1.6,0.8-2.8v-0.6c0-1.2-0.3-2.2-0.8-2.8c-0.5-0.7-1.3-1-2.3-1C182.5,36.8,181.1,36.8,181.1,36.8z"/>
		<path class="st3" d="M195.9,46.6V35.2h3.9c1.3,0,2.3,0.3,2.9,0.8s1,1.3,1,2.3c0,0.5-0.1,1-0.4,1.4s-0.7,0.7-1.2,1
			c0.6,0.2,1.1,0.5,1.4,0.9s0.5,1,0.5,1.7c0,1.1-0.3,1.9-1,2.5s-1.7,0.9-2.9,0.9h-4.2V46.6z M197.9,40h1.9c0.6,0,1.1-0.1,1.4-0.4
			c0.3-0.3,0.5-0.7,0.5-1.2c0-0.6-0.2-1-0.5-1.2s-0.8-0.4-1.5-0.4h-1.9V40H197.9z M197.9,41.5V45h2.2c0.6,0,1.1-0.2,1.5-0.5
			c0.3-0.3,0.5-0.7,0.5-1.3c0-1.2-0.6-1.8-1.8-1.8L197.9,41.5L197.9,41.5z"/>
		<path class="st3" d="M210.5,40.6l2.6-5.4h2.2l-3.8,7.2v4.2h-2v-4.2l-3.8-7.2h2.2L210.5,40.6z"/>
	</g>
</g>
</svg>
</div>

app/views/recipes/index.html.erb
<% if @appear %>
  <p>You appear to be visiting from <%= @appear %>.</p>
<% end %>

<%=form_tag recipes_path, method: :get, class: "mt-5 sm:flex sm:items-center" do %>
  <div class="w-full sm:max-w-xs">
    <%= text_field_tag :q, params[:q] || @appear, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
  </div>


<%= submit_tag "Go", class: "mt-3 w-full inline-flex items-center justify-center px-4 py-2 border border-transparent shadow-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm" %>
<% end %>
<ul class="space-y-6 mt-10 text-xl">
  <% @recipes.each do |recipe| %>
  <li><%= link_to recipe.data["title"], recipe_path(recipe, q: params[:q]), class: "text-indigo-600" %></li>
  <% end %>
</ul>

<% if !@recipes.empty? %>
<div class="block w-64 -ml-20 mt-8">
  <%= render '/recipes/edamam' %>
</div>
<% end %>

app/views/recipes/show.html.erb
<%= link_to recipes_path(q: params[:q]), class: "text-indigo-500" do %>
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-10 h-10 -ml-1">
  <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 15.75L3 12m0 0l3.75-3.75M3 12h18" />
</svg>
<% end %>

<% cache(@recipe) do %>
  <h1 class="text-3xl mt-6"><%= @recipe.data['title'] %></h1>

  <ul class="mt-8 mb-8">
  <% @recipe.data['ingredients'].each do |i| %>
  <li><%= i['text'] %></li>
  <% end %>
  <div>
  </ul>

  <% @recipe.data['instructions'].each do |i| %>
  <p class="mb-3 text-lg"><%= i['text'] %><p>
  <% end %>

<% end %>
<div class="block w-64 -ml-20 mt-8">
<%= render '/recipes/edamam' %>
</div>